### PR TITLE
feat: 🧑‍💻 Allow users to use jinja-templates to display first tab dynamically

### PR DESCRIPTION
**Pull request by spasma**
Hey @kinghat, 👋

Thanks for creating this awesome card! I missed the feature to dynamically show the tab, as I have some dynamic content for morning, afternoon and evening.

I also saw this discussion: https://github.com/kinghat/tabbed-card/discussions/70

For example I now use:
```
type: custom:tabbed-card
options:
  defaultTabIndex: '{% if now().hour > 17 %}2{% elif now().hour > 12 %}1{% else %}0{% endif %}'
```

to show different tabs by default based on the time of the day.

I've tested the old behaviour and all is still working. Please consider merging this PR.

Keep up the good work. 🎉

Sebastiaan

### CODE REVIEW

**Comment by ilearn2023au** [comment]
seems to be not working now.

**Comment by spasma** [comment]
It is working, but the JS in Home Assistant is cached for a long time. You cannot force to refresh it. After a while it will work.

**Comment by spasma** [comment]
i didn't hear anything from you in 4 months, so I changed it to a fork of your repo: https://github.com/spasma/tabbed-card-programmable

On some devices the cached js was still an issue on my HA-instance (even after core updates) as mentioned here: https://github.com/kinghat/tabbed-card/pull/105#issuecomment-1689501912, and I got bothered with updates to your repo. so I needed a solution for that asap.

**Comment by kinghat** [comment]
> i didn't hear anything from you in 4 months, so I changed it to a fork of your repo: https://github.com/spasma/tabbed-card-programmable
> 
> On some devices the cached js was still an issue on my HA-instance (even after core updates) as mentioned here: [#105 (comment)](https://github.com/kinghat/tabbed-card/pull/105#issuecomment-1689501912), and I got bothered with updates to your repo. so I needed a solution for that asap.

ya thats fine. im not saying its going to happen soon:tm: but i will eventually want to add dynamic templates to areas of the card. when the time comes, if youre still willing, i'd gladly accept your help.

**Comment by spasma** [comment]
yes, of course! no plans to add other features to it at the moment, but will keep it in sync with your changes for now. let me know if i can help anytime

**Comment by erkr** [comment]
@kinghat 
Thanks for fixing your card so quickly for Core 2025.5.x. But please reconsider merging in this pull request. I was using the [fork ](https://github.com/spasma/tabbed-card-programmable) mentioned above, till is was broken by core-2025.5.x, so reverted back to your version.
It really adds value to dynamically template defaultTabIndex. I can confirm that feature was working great over the last year.
Best Eric

**Comment by spasma** [comment]
@erkr I will update my fork (the @EnkodoNL one) next Wednesday, I'm on holiday now 🙂

**Comment by erkr** [comment]
No hurry. Enjoy 🙏

**Pull request closed without merging**
